### ISSUE TITLE
Parameter mismatch

### ISSUE THREAD

**Issue by robbagithub** [IBM-Blockchain/learn-chaincode#29] opened 2016-09-18 00:50 UTC
./chaincode_start.go:34: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
	*SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
		have Init(*shim.ChaincodeStub, string, []string) ([]byte, error)
		want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)

**Comment by masterDev1985** [comment] 2016-10-11 22:18
This is the same as #19 . Closing.

**Closed by masterDev1985** 2016-10-11 22:18 UTC

**Comment by ramarahul** [comment] 2017-05-31 12:08
@masterDev1985 I still am not able to fix it. Any help regarding this matter?

**Comment by masterDev1985** [comment] 2017-05-31 14:25
This error is caused by having the wrong version of fabric in your gopath.  You will need v0.6 of the fabric to be installed in your gopath.  These instructions should show you how to do that:

https://github.com/IBM-Blockchain/learn-chaincode/blob/master/docs/setup.md#hyperledger-fabric
