### ISSUE TITLE
When build the chaincode, it occurred errors.

### ISSUE THREAD

**Issue by Kimi1020** [IBM-Blockchain/learn-chaincode#22] opened 2016-09-05 05:52 UTC
When I am using below command to build the chaincode, it showed below errors. Could anyone tell me why this happened? It is very weird.

$go build ./
*SimpleChaincode does not implement shim.Chaincode(wrong type for Init method)

However, I didn't modify any go source files.

Thanks in advance.

**Comment by l2fprod** [comment] 2016-09-06 08:51
Same here.

```
C:\Users\Administrator\Documents\GoProjects\src\github.com\l2fprod\learn-chaincode\start>go build ./

# github.com/l2fprod/learn-chaincode/start
.\chaincode_start.go:34: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
        *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
                have Init(*shim.ChaincodeStub, string, []string) ([]byte, error)
                want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)
```

Looks like there was an API change in August:
https://github.com/hyperledger/fabric/commit/23afd05632b4ab62f364ec0c3a6468050407fae4#diff-838beed13b889e014387d59c649c90f1

It breaks this example and likely the Marbles chaincode too:
https://github.com/IBM-Blockchain/marbles-chaincode/blob/master/hyperledger/part1/part1_chaincode.go

**Comment by bellaj** [comment] 2016-09-07 23:31
the solution is just replace the parameter **stub *shim.ChaincodeStu** by **stub ChaincodeStubInterface** in all functions in both files  start/chaincode_start.go and finished/chaincode_finished.go

**Comment by dshuffma-ibm** [comment] 2016-09-09 16:12
^^ is correct, also this is duplicate of #19

**Closed by dshuffma-ibm** 2016-09-09 16:12 UTC
Labels: duplicate

**Comment by robbagithub** [comment] 2016-09-18 00:34
You'd think they would change the code no?

**Comment by robbagithub** [comment] 2016-09-18 00:43
With your fix I get the output
./chaincode_start.go:41: undefined: ChaincodeStubInterface
./chaincode_start.go:50: undefined: ChaincodeStubInterface
./chaincode_start.go:63: undefined: ChaincodeStubInterface

**Comment by pradeeppadmarajaiah** [comment] 2016-09-19 12:36
Change **stub *shim.ChaincodeStub** to  **stub shim.ChaincodeStubInterface**

pradeep@IBM015-PB7LWGP MINGW64 /c/Projects/GoProjects/src/github.com/learn-chaincode/start (master)
$ go build ./

**Comment by bellaj** [comment] 2016-12-28 20:38
I think this problem came from which fabric version is used..

**Comment by shaundennett** [comment] 2017-02-09 16:35
Getting the same issue.
Bluemix is stating that the Fabric version is 0.6 
I have tried to point the deploy to both the /finished go file in both the Master and V1.0 branches of git hub 
Both give me the same result :
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32001,
    "message": "Deployment failure",
    "data": "Error when deploying chaincode: Error getting chaincode package bytes: Error getting code 'go get' failed with error: \"exit status 1\"\npackage github.com/IBM-Blockchain/learn-chaincode/tree/master/finished: cannot find package \"github.com/IBM-Blockchain/learn-chaincode/tree/master/finished\" in any of:\n\t/opt/go/src/github.com/IBM-Blockchain/learn-chaincode/tree/master/finished (from $GOROOT)\n\t/opt/gopath/_usercode_/145730935/src/github.com/IBM-Blockchain/learn-chaincode/tree/master/finished (from $GOPATH)\n\t/opt/gopath/src/github.com/IBM-Blockchain/learn-chaincode/tree/master/finished\n"
  },
  "id": 1
}

Also tried this against my own chaincode git hub 
Does the currrent bluemix example work at all ???

**Comment by EasonWang01** [comment] 2017-02-23 08:17
git clone -b v0.5-developer-preview https://github.com/hyperledger-archives/fabric.git


0.5 works but 0.6 will cause this.

**Comment by dooglet** [comment] 2017-03-22 02:11
i think you need the v2.0 version of learn-chaincode to go with fabric v0.6. I had this error. remove the learn-chaincode and `git clone -b v2.0 https://github.com/dooglet/learn-chaincode.git
`

**Comment by EasonWang01** [comment] 2017-03-22 02:19
why hyperledger has so many company join but leave a poor doc?And always coming soon?
